[tasks.bindgen]
env_files = ["../.env"]
run_task = [
    { name = "bindgen-armpl", condition = { env = { "CARGO_MAKE_RUST_TARGET_ARCH" = "aarch64" } } },
    { name = "bindgen-mkl", condition = { env = { "CARGO_MAKE_RUST_TARGET_ARCH" = "x86" } } },
    { name = "bindgen-mkl", condition = { env = { "CARGO_MAKE_RUST_TARGET_ARCH" = "x86_64" } } },
]

[tasks.bindgen-armpl]
command = "bindgen"
args = [
    "${PATH_INCLUDE}/armpl.h",
    "-o",
    "src/armpl/armpl.rs",
    "--rust-target",
    "1.84",
    "--no-layout-tests",
    "--no-derive-debug",
    "--default-enum-style=newtype",
    "--allowlist-function",
    "cblas.*",
    "--allowlist-type",
    "cblas.*",
    "--allowlist-var",
    "^CBLAS.*$",
    "--",
    "-I",
    "${PATH_INCLUDE}",
    "-x",
    "c++",
]

[tasks.bindgen-mkl]
command = "bindgen"
args = [
    "${PATH_INCLUDE}/mkl_cblas.h",
    "-o",
    "src/mkl/cblas.rs",
    "--rust-target",
    "1.84",
    "--no-layout-tests",
    "--no-derive-debug",
    "--default-enum-style=newtype",
    "--allowlist-function",
    "cblas.*",
    "--allowlist-type",
    "cblas.*",
    "--allowlist-var",
    "^CBLAS.*$",
    "--",
    "-I",
    "${PATH_INCLUDE}/..",
    "-x",
    "c++",
]
